export const GENERATED_CLUES = {
  "feast": "A word meaning: A very large meal, often of a ceremonial nature.",
  "clean": "A word meaning: Free of dirt, filth, or impurities ; not dirty, filthy, or soiled.",
  "hear": "A word meaning: To perceive sounds through the ear.",
  "bead": "A word meaning: A small, round object with a hole to allow it to be threaded on a cord or wire.",
  "deal": "A word meaning: An indefinite quantity or amount; a lot .",
  "flea": "A word meaning: A small, wingless, parasitic insect of the order Siphonaptera.",
  "dear": "A word meaning: Loved; lovable.",
  "sneak": "A word meaning: One who sneaks; one who moves stealthily to acquire an item or information.",
  "bean": "A word meaning: Any plant of several genera of the taxonomic family Fabaceae that produces large edible seeds or edible seedpods.",
  "cheat": "A word meaning: To violate rules in order to gain, or attempt to gain, advantage from a situation.",
  "fear": "A word meaning: A strong, unpleasant emotion or feeling caused by actual or perceived danger or threat.",
  "dream": "A word meaning: Imaginary events seen in the mind while sleeping.",
  "heal": "A word meaning: To make better from a disease, wound, etc.",
  "fail": "A word meaning: To be unsuccessful.",
  "braid": "A word meaning: To weave together, intertwine ; to arrange in braids.",
  "plain": "A word meaning: Simple, unaltered.",
  "maid": "A word meaning: A female servant or cleaner .",
  "rain": "A word meaning: Condensed water falling from a cloud.",
  "paid": "A word meaning: That is not free of charge; that costs money.",
  "chain": "A word meaning: A series of interconnected rings or links usually made of metal.",
  "clear": "A word meaning: Transparent in colour.",
  "jail": "A word meaning: A place or institution for the confinement of persons held against their will in lawful custody or detention.",
  "ail": "A word meaning: To be ill; to suffer; to be troubled.",
  "train": "A word meaning: Elongated or trailing portion.",
  "feed": "A word meaning: To give food to eat.",
  "rail": "A word meaning: A horizontal bar extending between supports and used for support or as a barrier.",
  "hail": "A word meaning: Balls or pieces of ice falling as precipitation, often in connection with a thunderstorm.",
  "cheek": "A word meaning: The soft skin on each side of the face, below the eyes.",
  "week": "A word meaning: Any period of seven consecutive days.",
  "wheel": "A word meaning: A circular device capable of rotating on its axis, facilitating movement or transportation or performing labour in machines.",
  "paint": "A word meaning: A substance that is applied as a liquid or paste, and dries into a solid coating that protects or adds colour to an object or surface to which it...",
  "sweet": "A word meaning: Tasting of sugars.",
  "tree": "A word meaning: A perennial woody plant taller and larger than a shrub with a wooden trunk and, at some distance from the ground, having leaves and branches.",
  "beet": "A word meaning: A beetroot; a swollen root of such a plant used as a culinary vegetable.",
  "sheep": "A word meaning: A woolly ruminant of the genus Ovis.",
  "sleep": "A word meaning: To rest in a state of reduced consciousness.",
  "deer": "A word meaning: A ruminant mammal with hooves and often antlers, of the family Cervidae, or one of several similar animals from related families of the order...",
  "coat": "A word meaning: An outer garment covering the upper torso and arms.",
  "coach": "A word meaning: A trainer or instructor.",
  "float": "A word meaning: To be supported by a fluid of greater density .",
  "feet": "A word meaning: Fact; performance; feat.",
  "steer": "A word meaning: To guide the course of a vessel, vehicle, aircraft etc.",
  "goal": "A word meaning: A result that one is attempting to achieve.",
  "meet": "A word meaning: To make contact while in proximity.",
  "throat": "A word meaning: The front part of the neck.",
  "boat": "A word meaning: A craft used for transportation of goods, fishing, racing, recreational cruising, or military use on or in the water, propelled by oars or...",
  "queen": "A word meaning: A female monarch.",
  "loaf": "A word meaning: A block of bread after baking.",
  "toad": "A word meaning: An amphibian, a kind of frog with shorter hindlegs and a drier, wartier skin, many in family Bufonidae.",
  "coal": "A word meaning: A black or brownish black rock formed from prehistoric plant remains, composed largely of carbon and burned as a fuel.",
  "road": "A word meaning: A way used for travelling between places, originally one wide enough to allow foot passengers and horses to travel.",
  "loan": "A word meaning: A sum of money or other property that a natural or legal person borrows from another with the condition that it be returned or repaid over time or...",
  "juice": "A word meaning: A liquid made from plant, especially fruit.",
  "toast": "A word meaning: Bread that has been toasted .",
  "soap": "A word meaning: A metallic salt derived from a fatty acid, commonly used in cleaning products.",
  "build": "A word meaning: To form by combining materials or parts.",
  "cruise": "A word meaning: A sea or lake voyage, especially one taken for pleasure.",
  "bruise": "A word meaning: A purplish mark on the skin due to leakage of blood from capillaries under the surface that have been damaged by a blow.",
  "fluid": "A word meaning: A liquid .",
  "goat": "A word meaning: Any hoofed mammal of the genus Capra.",
  "guilt": "A word meaning: Responsibility for wrongdoing.",
  "suit": "A word meaning: A set of clothes to be worn together, now especially a man's matching jacket and trousers , or a similar outfit for a woman.",
  "fruit": "A word meaning: The seed-bearing part of a plant; often edible, colourful, fragrant, and sweet or sour; produced from a floral ovary after fertilization.",
  "recruit": "A word meaning: To enroll or enlist new members or potential employees on behalf of an employer, organization, sports team, the military, etc.",
  "pie": "A word meaning: A type of pastry that consists of an outer crust and a filling.",
  "quick": "A word meaning: Moving with speed, rapidity or swiftness, or capable of doing so.",
  "guide": "A word meaning: Someone who guides, especially someone hired to show people around a place or an institution and offer information and explanation, or to lead...",
  "built": "A word meaning: Well-this word, muscular or toned.",
  "guitar": "A word meaning: A stringed musical instrument, of European origin, usually with a fretted fingerboard and six strings, played with the fingers or a plectrum .",
  "tie": "A word meaning: A knot; a fastening.",
  "view": "A word meaning: The act of seeing or looking at something.",
  "lie": "A word meaning: To rest in a horizontal position on a surface.",
  "dries": "A word meaning: Without water or moisture, said of something that has previously been wet or moist.",
  "shield": "A word meaning: Anything that protects or defends; defense; shelter; protection.",
  "cried": "A word meaning: To shed tears; to weep, especially in anger or sadness.",
  "fried": "A word meaning: Cooked by frying.",
  "niece": "A word meaning: A daughter of one’s sibling, brother-in-law, or sister-in-law.",
  "piece": "A word meaning: A part of a larger whole, usually in such a form that it is able to be separated from other parts.",
  "shriek": "A word meaning: To utter a loud, sharp, shrill sound or cry, as do some birds and beasts.",
  "thief": "A word meaning: One who steals another person's property, especially by stealth and without using force or violence.",
  "flies": "A word meaning: The open area above a stage where scenery and equipment may be hung.",
  "tried": "A word meaning: Tested, hence, proven to be firm or reliable.",
  "germ": "A word meaning: A pathogen: a pathogenic microorganism, such as a bacterium or virus.",
  "nerve": "A word meaning: Courage; boldness; audacity; gall.",
  "serve": "A word meaning: To provide a service .",
  "fewer": "A word meaning: Quantifier meaning a smaller number of.",
  "term": "A word meaning: That which limits the extent of anything; limit, extremity, bound, boundary, terminus.",
  "caper": "A word meaning: A prank or practical joke.",
  "sister": "A word meaning: A daughter of the same parents as another person.",
  "tower": "A word meaning: Any very tall building or structure; skyscraper.",
  "bird": "A word meaning: An animal of the clade Aves in the phylum Chordata, characterized by being warm-blooded, having feathers and wings usually capable of flight,...",
  "third": "A word meaning: The ordinal form of the cardinal number three.",
  "firm": "A word meaning: A business partnership; the name under which it trades.",
  "first": "A word meaning: Preceding all others of a series or kind; the ordinal of one; earliest.",
  "skirt": "A word meaning: A separate article of clothing, usually worn by women and girls, that hangs from the waist and covers the lower torso and part of the legs.",
  "girl": "A word meaning: A female child.",
  "stir": "A word meaning: To disturb the relative position of the particles by passing an object through it.",
  "shirt": "A word meaning: An article of clothing that is worn on the upper part of the body, and often has sleeves, either long or short, that cover the arms.",
  "hard": "A word meaning: Solid and firm.",
  "mark": "A word meaning: Boundary, land within a boundary.",
  "farm": "A word meaning: A place where agricultural and similar activities take place.",
  "star": "A word meaning: Any small, natural and bright dot in the sky, most visible in the night or twilight sky.",
  "part": "A word meaning: A portion; a component.",
  "cart": "A word meaning: A shopping this word.",
  "start": "A word meaning: The beginning of an activity.",
  "dark": "A word meaning: Having an absolute or relative lack of light.",
  "born": "A word meaning: Having from birth a certain quality or character.",
  "corn": "A word meaning: Any cereal plant that is the main crop or staple of a country or region.",
  "fork": "A word meaning: Any of several types of pronged tools , as follows.",
  "horse": "A word meaning: A hoofed mammal, Equus ferus caballus, often used throughout history for riding and draft work.",
  "short": "A word meaning: Having a small distance from one end or edge to another, either horizontally or vertically.",
  "north": "A word meaning: The direction towards the pole to the left-hand side of someone facing east, specifically 0°, or the direction towards the pole lying on the...",
  "blur": "A word meaning: To make indistinct or hazy, to obscure or dim.",
  "adorn": "A word meaning: To make more beautiful and attractive; to decorate.",
  "surf": "A word meaning: To ride a wave on a surfboard; to pursue or take part in the sport of surfing.",
  "torn": "A word meaning: Unable to decide between multiple options.",
  "burnt": "A word meaning: Damaged or injured by fire or heat.",
  "burst": "A word meaning: To break from internal pressure.",
  "burp": "A word meaning: A belch.",
  "nurse": "A word meaning: A person involved in providing direct care for the sick.",
  "curl": "A word meaning: A curving piece or lock of hair; a ringlet.",
  "hurt": "A word meaning: To cause physical pain and/or injury.",
  "redo": "A word meaning: To do again.",
  "dislike": "A word meaning: To have a feeling of aversion or antipathy towards.",
  "return": "A word meaning: To come or go back .",
  "reheat": "A word meaning: To heat something after it has cooled off.",
  "rerun": "A word meaning: A television program shown after its initial presentation.",
  "rewind": "A word meaning: To wind back, now especially of a cassette or a video tape, CD, DVD etc.",
  "unlock": "A word meaning: To undo or open a lock or something locked by, for example, turning a key, or selecting a combination.",
  "retie": "A word meaning: To tie again; to tie something that has already been tied or was tied before.",
  "decide": "A word meaning: To resolve ; to choose, determine, or settle.",
  "rewrite": "A word meaning: To write again, differently; to modify; to revise.",
  "unhook": "A word meaning: To remove from a hook.",
  "unlucky": "A word meaning: Unfortunate, marked by misfortune.",
  "unplug": "A word meaning: To disconnect from a supply, especially an electrical socket.",
  "unsafe": "A word meaning: Not safe ; dangerous.",
  "untie": "A word meaning: To free from fastening or from restraint; to let loose; to unbind.",
  "untrue": "A word meaning: False; not true.",
  "unzip": "A word meaning: To restore to its original form, from a zip file.",
  "uphill": "A word meaning: Up a slope, towards higher ground.",
  "mislead": "A word meaning: To deceive by telling lies or otherwise giving a false impression.",
  "preheat": "A word meaning: To heat beforehand or in advance, to heat something in preparation for further action.",
  "unpack": "A word meaning: To remove from a package or container, particularly with respect to items that had previously been arranged closely and securely in a pack.",
  "project": "A word meaning: A planned endeavor, usually with a specific goal and accomplished in several steps or stages.",
  "protect": "A word meaning: To keep safe; to defend; to guard; to prevent harm coming to.",
  "preschool": "A word meaning: A nursery school.",
  "acted": "A word meaning: An instance of a certain standardized college admissions test in the United States.",
  "rainy": "A word meaning: Pouring with rain; wet; showery.",
  "calmly": "A word meaning: In a calm manner; coolly.",
  "cloudy": "A word meaning: Covered with or characterised by clouds.",
  "golden": "A word meaning: Made of, or relating to, gold.",
  "endless": "A word meaning: Having no end.",
  "harden": "A word meaning: To make something hard or harder.",
  "drinkable": "A word meaning: Safe to drink.",
  "shorten": "A word meaning: To make shorter; to abbreviate.",
  "shortly": "A word meaning: In a short or brief time or manner; quickly.",
  "singer": "A word meaning: A person who sings, often professionally.",
  "helpful": "A word meaning: Furnishing help; giving aid; useful.",
  "jumped": "A word meaning: To propel oneself rapidly upward, downward and/or in any horizontal direction such that momentum causes the body to become airborne.",
  "forgetful": "A word meaning: Unable to remember things well; liable to forget.",
  "homeless": "A word meaning: Lacking a permanent place of residence.",
  "hopeless": "A word meaning: Without hope; despairing; not expecting anything positive.",
  "lasting": "A word meaning: Persisting for an extended period of time.",
  "kindness": "A word meaning: The state of being kind.",
  "useful": "A word meaning: Having a practical or beneficial use.",
  "watched": "A word meaning: Monitored.",
  "musical": "A word meaning: Of, belonging or relating to music, or to its performance or notation.",
  "colder": "A word meaning: Having a low temperature.",
  "wooden": "A word meaning: Made of wood.",
  "meeting": "A word meaning: A gathering of persons for a purpose; an assembly.",
  "airline": "A word meaning: A company that flies airplanes to transport people and goods.",
  "anyone": "A word meaning: Any particle that obeys a continuum of quantum statistics, only two of which are the standard Bose-Einstein and Fermi-Dirac statistics.",
  "airplane": "A word meaning: A powered heavier-than-air aircraft with fixed wings.",
  "anyplace": "A word meaning: At a non-specific place; anywhere.",
  "backbone": "A word meaning: The series of vertebrae, separated by disks, that encloses and protects the spinal cord, and runs down the middle of the back in vertebrate animals.",
  "background": "A word meaning: A part of the picture that depicts scenery to the rear or behind the main subject.",
  "anybody": "A word meaning: A person of some importance.",
  "backyard": "A word meaning: A yard to the rear of a house or similar residence.",
  "cannot": "A word meaning: Can not .",
  "bathroom": "A word meaning: A room containing a shower or bathtub, and a toilet.",
  "campfire": "A word meaning: A fire at a campground or on a camping trip, often used for cooking, to provide light and heat, to drive away bugs, and as a focal point for...",
  "classmate": "A word meaning: A student who is in the same class at school.",
  "cookbook": "A word meaning: A book or an encyclopedia of recipes and cookery tips.",
  "daytime": "A word meaning: The time of daylight; the time between sunrise and sunset.",
  "earring": "A word meaning: A piece of jewelry worn on the ear.",
  "doorbell": "A word meaning: A bell, buzzer, or chime device mounted on or adjacent to a door's exterior, meant to be rung by a visitor to announce one's presence.",
  "forever": "A word meaning: For all time, for all eternity; for a lifetime; for an infinite amount of time.",
  "fireplace": "A word meaning: An open hearth for holding a fire at the base of a chimney.",
  "headset": "A word meaning: A pair of headphones or earphones, or a singular headphone or earphone, typically with an attached microphone.",
  "football": "A word meaning: A sport played on foot in which teams attempt to get a ball into a goal or zone defended by the other team.",
  "goldfish": "A word meaning: A type of small fish, Carassius auratus, typically orange-colored.",
  "homemade": "A word meaning: Made at home.",
  "indoor": "A word meaning: Situated in, or designed to be used in, or carried on within, the interior of a building.",
  "maybe": "A word meaning: Perhaps, possibly.",
  "myself": "A word meaning: N the eleventh studio album by Taiwanese singer Jolin Tsai, released by Warner and Mars on August 13, 2010.",
  "outside": "A word meaning: The space beyond some limit or boundary.",
  "notebook": "A word meaning: A book in which notes or memoranda are written.",
  "popcorn": "A word meaning: A snack food made from corn or maize kernels popped by dry heating.",
  "pancake": "A word meaning: A thin batter cake fried in a pan or on a griddle in oil or butter.",
  "seafood": "A word meaning: Food from the sea, including that derived from fish, shellfish, crustaceans, cephalopods, algae, marine mammals, and other marine organisms.",
  "raincoat": "A word meaning: A waterproof coat to be worn in the rain.",
  "scarecrow": "A word meaning: An effigy, typically made of straw and dressed in old clothes, fixed to a pole in a field to deter birds from eating crops or seeds planted there.",
  "sailboat": "A word meaning: A boat propelled by a sail.",
  "showoff": "A word meaning: Alternative form of show-off. [One who shows off.",
  "seashell": "A word meaning: The empty shell of a marine mollusk.",
  "sidewalk": "A word meaning: A paved footpath located at the side of a road, for the use of pedestrians.",
  "skateboard": "A word meaning: A narrow, wooden or plastic platform mounted on pairs of wheels, on which one stands and propels oneself by pushing along the ground with one foot.",
  "snowman": "A word meaning: A humanoid figure made with large snowballs stacked on each other.",
  "snowball": "A word meaning: A ball of snow, usually one made in the hand and thrown for amusement in a this word fight.",
  "snowfall": "A word meaning: The amount of snow that falls on one occasion.",
  "softball": "A word meaning: A game similar to baseball but played with a larger and softer ball which can be thrown overhand or underhand.",
  "someone": "A word meaning: A partially specified but unnamed person.",
  "starfish": "A word meaning: Any of various echinoderms with usually five arms, many of which eat bivalves or corals by everting their stomach.",
  "springtime": "A word meaning: The season of spring, between winter and summer.",
  "sundown": "A word meaning: A hat with a wide brim to shade the eyes from sunlight.",
  "textbook": "A word meaning: A coursebook, a formal manual of instruction in a specific subject.",
  "upstairs": "A word meaning: Located on a higher floor or level of a building.",
  "after": "A word meaning: Behind; later in time; following.",
  "again": "A word meaning: Another time: indicating a repeat of an action.",
  "always": "A word meaning: At all times; throughout all time; since the beginning.",
  "animal": "A word meaning: Any member of the kingdom Animalia of multicellular organisms that are usually mobile, whose cells are not encased in a rigid cell wall and which...",
  "along": "A word meaning: Onward, forward, with progressive action.",
  "answer": "A word meaning: A response or reply; something said or done in reaction to a statement or question.",
  "around": "A word meaning: So as to form a circle or trace a circular path, or approximation thereof.",
  "away": "A word meaning: From a place, hence.",
  "because": "A word meaning: On account, for sake [with of].",
  "before": "A word meaning: At an earlier time.",
  "between": "A word meaning: A kind of needle, shorter than a sharp, with a small rounded eye, used for making fine stitches on heavy fabrics.",
  "change": "A word meaning: To become something different.",
  "even": "A word meaning: Equal in proportion, quantity, size, etc.",
  "different": "A word meaning: Not the same; exhibiting a difference.",
  "every": "A word meaning: A surname.",
  "example": "A word meaning: Something that is representative of all such things in a group.",
  "father": "A word meaning: A male parent, especially of a human; a male who parents a child .",
  "follow": "A word meaning: To go after; to pursue; to move behind in the same path or direction.",
  "give": "A word meaning: To move, shift, provide something abstract or concrete to someone or something or somewhere.",
  "great": "A word meaning: Very good; excellent; wonderful; fantastic.",
  "group": "A word meaning: A number of things or persons being in some relation to one another.",
  "heard": "A word meaning: That has been perceived aurally.",
  "high": "A word meaning: Physically elevated, extending above a base or average level.",
  "house": "A word meaning: A structure built or serving as an abode of human beings.",
  "large": "A word meaning: Of considerable or relatively great size or extent.",
  "kind": "A word meaning: Having a benevolent, courteous, friendly, generous, gentle, liberal, sympathetic, or warm-hearted nature or disposition, marked by consideration...",
  "learn": "A word meaning: To acquire, or attempt to acquire knowledge or an ability to do something.",
  "letter": "A word meaning: A symbol in an alphabet.",
  "light": "A word meaning: Electromagnetic radiation in the wavelength range visible to the human eye : visible this word.",
  "little": "A word meaning: Small in size.",
  "mean": "A word meaning: To intend.",
  "might": "A word meaning: Simple past of may.",
  "mother": "A word meaning: A female parent, especially of a human; a female who parents a child .",
  "much": "A word meaning: To a great extent.",
  "never": "A word meaning: At no time; on no occasion; in no circumstance.",
  "move": "A word meaning: To change place or posture; to go, in any manner, from one place or position to another.",
  "picture": "A word meaning: A representation of anything upon canvas, paper, or other surface, by drawing, painting, printing, photography, etc.",
  "place": "A word meaning: An area; somewhere within an area.",
  "point": "A word meaning: A small dot or mark.",
  "rolled": "What a ball did when it moved along the ground.",
  "read": "A word meaning: To look at and interpret letters or other information that is written.",
  "school": "A word meaning: An institution dedicated to teaching and learning.",
  "study": "A word meaning: To review materials already learned in order to make sure one does not forget them, usually in preparation for an examination.",
  "fingers": "The five parts at the end of your hand.",
  "sentence": "A word meaning: A grammatically complete series of words consisting of a subject and predicate, even if one or the other is implied.",
  "though": "A word meaning: Despite that; however.",
  "thought": "A word meaning: A representation created in the mind without the use of one's faculties of vision, sound, smell, touch, or taste.",
  "three": "A word meaning: The digit/figure 3.",
  "while": "A word meaning: An uncertain duration of time, a period of time.",
  "together": "A word meaning: At the same time, in the same place; in close association or proximity.",
  "world": "A word meaning: The subjective human experience, regarded collectively.",
  "usually": "A word meaning: Most of the time; less than always, but more than occasionally.",
  "year": "A word meaning: The length of a this word as marked by a calendar, 365 or 366 days in the Gregorian calendar.",
  "hours": "A word meaning: An indefinite period of time.",
  "byte": "A word meaning: A unit of computing storage equal to eight bits, which can represent any of 256 distinct values.",
  "couldn't": "A short way to say could not.",
  "twenty": "A word meaning: The numbers this word to this word-nine .",
  "extend": "A word meaning: To cause to increase in extent.",
  "character": "A word meaning: A being involved in the action of a story.",
  "except": "A word meaning: To exclude; to specify as being an exception.",
  "friends": "A word meaning: The Quakers; the Society of this word.",
  "speed": "A word meaning: The state of moving quickly or the capacity for rapid motion.",
  "products": "A word meaning: Any tangible or intangible good or service that is a result of a process and that is intended for delivery to a customer or end user.",
  "keyboard": "A word meaning: A set of keys laid out in a grid-like pattern, used for typing on a typewriter, computer etc.",
  "monitor": "A word meaning: A device similar to a television set used as to give a graphical display of the output from a computer.",
  "whom": "A word meaning: N an American radio station which airs an adult contemporary radio format.",
  "whine": "A word meaning: To utter a high-pitched cry.",
  "happened": "A word meaning: To occur or take place.",
  "vowel": "A word meaning: A sound produced by the vocal cords with relatively little restriction of the oral cavity, forming the prominent sound of a syllable.",
  "order": "A word meaning: A command.",
  "questions": "A word meaning: A game in which players must only say this word, and if they don't they lose.",
  "measure": "A word meaning: A prescribed quantity or extent.",
  "portal": "A word meaning: An entrance, entry point, or means of entry.",
  "catch": "A word meaning: The act of seizing or capturing.",
  "villain": "A word meaning: A character who has the role of being bad.",
  "tunnel": "A word meaning: An underground or underwater passage.",
  "basin": "A word meaning: A depression, natural or artificial, containing water.",
  "remember": "A word meaning: To recall from one's memory; to have an image in one's memory.",
  "early": "A word meaning: Arriving a time before expected; sooner than on time.",
  "carton": "A word meaning: An inexpensive, disposable box-like container fashioned from either paper, paper with wax-covering , or other lightweight material.",
  "utensil": "A word meaning: An instrument or device for domestic use, especially in the kitchen.",
  "pastel": "A word meaning: Any of several subdued tints of colors, usually associated with pink, peach, yellow, green, blue, and lavender.",
  "button": "A word meaning: A knob or disc that is passed through a loop or , serving as a fastener.",
  "become": "A word meaning: Begin to be; turn into .",
  "mortal": "A word meaning: Susceptible to death by aging, sickness, injury, or wound.",
  "bargain": "A word meaning: An item purchased for significantly less than the usual, or recommended, price.",
  "numerical": "A word meaning: Of or pertaining to numbers.",
  "vocal": "A word meaning: Of, pertaining to, or resembling the human voice or speech.",
  "muffin": "A word meaning: A cupcake-shaped baked good , sometimes glazed but typically without frosting, eaten especially for breakfast .",
  "certain": "A word meaning: Sure in one's mind, positive; absolutely confident in the truth of something.",
  "fatal": "A word meaning: Causing death or destruction.",
  "oxen": "More than one ox.",
  "pumpkin": "A word meaning: The round yellow or orange fruit of this plant.",
  "mental": "A word meaning: Of or relating to the mind or specifically the total emotional and intellectual response of an individual to external reality.",
  "oval": "A word meaning: An elongated round shape resembling an egg or ellipse.",
  "orphan": "A word meaning: A person, especially a minor, both or one of whose parents have died.",
  "apron": "A word meaning: An article of clothing worn over the front of the torso and/or legs for protection from spills.",
  "neutral": "A word meaning: Not taking sides in a conflict such as war.",
  "towel": "A word meaning: A cloth used for wiping, especially one used for drying anything wet, such as a person after a bath.",
  "cannon": "A word meaning: A complete assembly, consisting of an artillery tube and a breech mechanism, firing mechanism or base cap, which is a component of a gun, howitzer...",
  "anvil": "A word meaning: A heavy iron block used in the blacksmithing trade as a surface upon which metal can be struck and shaped.",
  "chapel": "A word meaning: A place of worship, smaller than or subordinate to a church.",
  "poison": "A word meaning: A substance that is harmful or lethal to a living organism when ingested.",
  "fountain": "A word meaning: An artificial, usually ornamental, water feature consisting of one or more streams of water originating from a statue or other structure.",
  "tinsel": "A word meaning: A thin, shiny foil for ornamental purposes which is of a material made of metal or resembling metal.",
  "landform": "A word meaning: Any geological feature, such as a mountain or valley.",
  "latitude": "A word meaning: The relative freedom from restrictions; scope to do something.",
  "council": "A word meaning: A committee that leads or governs .",
  "abundant": "A word meaning: Fully sufficient; found in copious supply; in great quantity; overflowing.",
  "prime": "A word meaning: First in importance, degree, or rank.",
  "thrive": "A word meaning: To increase in wealth or success; to prosper, be profitable.",
  "distributive": "A word meaning: Relating to distribution.",
  "compass": "A word meaning: A magnetic or electronic device used to determine the cardinal directions .",
  "compatible": "A word meaning: Able to get along well.",
  "longitude": "A word meaning: Angular distance measured west or east of the prime meridian.",
  "composite": "A word meaning: Made up of multiple components; compound or complex.",
  "canopy": "A word meaning: The zone of the highest foliage and branches of a forest.",
  "consumer": "A word meaning: Someone who trades money for goods or services as an individual.",
  "wildfire": "A word meaning: A rapidly spreading fire, especially one occurring in a wildland area.",
  "absolute": "A word meaning: Free of restrictions, limitations, qualifications or conditions.",
  "nutrients": "A word meaning: N an open access peer-reviewed scientific journal publishing reviews, regular research papers, and short communications on all aspects of nutrition.",
  "equator": "A word meaning: An imaginary great circle around Earth, equidistant from the two poles, and dividing earth's surface into the northern and southern hemispheres.",
  "producer": "A word meaning: An individual or organization that creates goods and services.",
  "resist": "A word meaning: To oppose; to refuse to accept.",
  "tropical": "A word meaning: Of or pertaining to the tropics, the equatorial region between 23 degrees north and 23 degrees south.",
  "deposit": "A word meaning: Money placed in a bank account, as for safekeeping or to earn interest.",
  "retain": "A word meaning: Often followed by from: to hold back ; to check, to prevent, to restrain, to stop.",
  "pollinator": "A word meaning: The agent that pollinates a plant; often an insect.",
  "compensation": "A word meaning: The act or principle of compensating.",
  "twelve": "A word meaning: A group of this word items.",
  "dispersal": "A word meaning: The act or result of dispersing or scattering.",
  "yourself": "A word meaning: A male given name from Arabic.",
  "thirty": "A word meaning: A commercial lasting 30 seconds.",
  "vegetable": "A word meaning: A plant raised for some edible part of it, such as the leaves, roots, fruit or flowers, but excluding any plant considered to be a fruit, grain,...",
  "proverb": "A word meaning: A commonly used sentence expressing popular wisdom.",
  "synonym": "A word meaning: A term which is synonymous with others.",
  "antonym": "A word meaning: A word which has the opposite meaning of another word.",
  "across": "A word meaning: From one side to the other.",
  "slowly": "A word meaning: At a slow pace.",
  "tomatoes": "A word meaning: The savory fruit of this plant, most often red when ripe, treated as a vegetable in horticulture and cooking.",
  "today": "A word meaning: On the current day or date.",
  "problem": "A word meaning: A difficulty that has to be resolved or dealt with.",
  "complete": "A word meaning: To make whole or entire.",
  "usefulness": "A word meaning: The quality or degree of being useful.",
  "potato": "A word meaning: A plant of species Solanum tuberosum or its edible starchy tuber.",
  "rather": "A word meaning: Used to specify a choice or preference; preferably, in preference to.",
  "during": "A word meaning: A surname.",
  "covered": "A word meaning: Overlaid or enclosed .",
  "carrot": "A word meaning: A vegetable with a nutritious, juicy, sweet root that is often orange in colour, Daucus carota, family Apiaceae.",
  "crowd": "A word meaning: To press forward; to advance by pushing.",
  "onion": "A word meaning: A monocotyledonous plant , allied to garlic, used as vegetable and spice.",
  "metaphor": "A word meaning: The use of a word, phrase, concept, or set of concepts to refer to something other than its literal meaning, invoking an implicit similarity...",
  "simile": "A word meaning: A figure of speech in which one thing is explicitly compared to another, using e.g.",
  "since": "A word meaning: From a specified time in the past.",
  "jungle": "A word meaning: A large, undeveloped, humid forest, especially in a tropical region, that is home to many wild plants and animals.",
  "several": "A word meaning: A number of different; various.",
  "fresh": "A word meaning: Newly produced or obtained; recent.",
  "quiz": "A word meaning: A competition in the answering of questions.",
  "crumble": "A word meaning: A dessert of British origin containing stewed fruit topped with a crumbly mixture of fat, flour, and sugar.",
  "juvenile": "A word meaning: Young; not fully developed.",
  "however": "A word meaning: Nevertheless; yet, still; in spite of that.",
  "reptile": "A word meaning: Any member of the class Reptilia that is not a bird— a cold-blooded vertebrate with dry scales that usually lays eggs, such as a lizard, snake,...",
  "voice": "A word meaning: Sound uttered by the mouth, especially by human beings in speech or song.",
  "cotton": "A word meaning: A soft, fibrous, usually white substance consisting of fine hairs.",
  "toward": "A word meaning: Approaching, coming near; impending; present, at hand.",
  "proposal": "A word meaning: Something which is proposed, or offered for consideration or acceptance.",
  "puzzle": "A word meaning: A thing such as a complicated matter or a problem which is difficult to make sense of or understand.",
  "colon": "A word meaning: Part of the large intestine; the final segment of the digestive system, after the ileum and before the rectum.",
  "bridal": "A word meaning: Of or pertaining to a bride, or to wedding.",
  "fragile": "A word meaning: Easily broken, not sturdy; of delicate material.",
  "ankle": "A word meaning: The skeletal joint which connects the foot with the leg.",
  "dental": "A word meaning: Of or concerning the teeth.",
  "hostile": "A word meaning: Not friendly; appropriate to an enemy; showing the disposition of an enemy; showing ill will and malevolence or a desire to thwart and injure.",
  "children": "A word meaning: A surname.",
  "heaven": "A word meaning: The abode of God or the gods, traditionally conceived as beyond the sky.",
  "mobile": "A word meaning: Pertaining to or by agency of this word phones.",
  "gerbil": "A word meaning: A member of one of several species of small, jumping, mouselike rodents of the subfamily Gerbillinae, native to Africa, India, and Southern Europe.",
  "freckle": "A word meaning: A small brownish or reddish pigmentation spot on the surface of the skin.",
  "knuckle": "A word meaning: Any of the joints between the bones of the fingers.",
  "satin": "A word meaning: A cloth woven from silk, nylon or polyester with a glossy surface and a dull back.",
  "nasal": "A word meaning: Of or pertaining to the nose or to the nasion.",
  "tonsil": "A word meaning: Any of various small masses of lymphoid tissues.",
  "sprinkle": "A word meaning: To cause to fall in fine drops or small pieces .",
  "postal": "A word meaning: Relating to the collection, sorting and delivery of mail.",
  "penguin": "A word meaning: Any of several flightless sea birds, of the family Spheniscidae within the order Sphenisciformes, found in the Southern Hemisphere, marked by...",
  "evil": "A word meaning: Intending to harm; malevolent.",
  "dimple": "A word meaning: Specifically, a small natural depression on the skin.",
  "hemisphere": "A word meaning: Half of the Earth, such as the Northern this word, Southern this word, Western this word or Eastern this word, Land this word, Water this word etc.",
  "commutative": "A word meaning: Such that the order in which the operands are taken does not affect their image under the operation.",
  "terrarium": "A word meaning: A partially enclosed glass container for displaying plants.",
  "camouflage": "A word meaning: The use of natural or artificial material on personnel, objects, or tactical positions with the aim of confusing, misleading, or evading the enemy.",
  "associative": "A word meaning: Pertaining to, resulting from, or characterised by association.",
  "climate": "A word meaning: The long-term manifestations of weather and other atmospheric conditions in a given area or country.",
  "depend": "A word meaning: To trust; to have confidence; to rely.",
  "habitat": "A word meaning: A range; a place where a species naturally occurs.",
  "inverse": "A word meaning: Opposite in effect, nature or order.",
  "ecosystem": "A word meaning: A system formed by an ecological community and its environment that functions as a unit.",
  "destroyed": "A word meaning: Damaged beyond repair; ruined; wrecked; obliterated.",
  "hibernate": "A word meaning: To spend the winter in a dormant or inactive state of minimal activity, low body temperature, slow breathing and heart rate, and low metabolic rate.",
  "community": "A word meaning: A group sharing common characteristics, such as the same language, law, religion, or tradition.",
  "population": "A word meaning: The people living within a political or geographical boundary.",
  "mimicry": "A word meaning: An act or ability to simulate or effect the appearance, characteristics, or behavior of someone or something else.",
  "resource": "A word meaning: Something that one uses to achieve an objective, e.g.",
  "reproduce": "A word meaning: To generate or propagate offspring or organisms sexually or asexually.",
  "rainforest": "A word meaning: A forest in a climate with high annual rainfall and no dry season.",
  "factory": "A word meaning: A building or other place where manufacturing takes place.",
  "predator": "A word meaning: Any animal or other organism that hunts and kills other nonplant organisms , primarily for food.",
  "organism": "A word meaning: A discrete and complete living thing, such as animal, plant, fungus or microorganism.",
  "taiga": "A word meaning: A subarctic zone of evergreen coniferous forests situated south of the tundras and north of the steppes in the Northern Hemisphere.",
  "mountain": "A word meaning: An elevation of land of considerable dimensions rising more or less abruptly, forming a conspicuous figure in the landscape, usually having a...",
  "prey": "A word meaning: A living thing, usually an animal, that is eaten by another living thing.",
  "forty": "A word meaning: Resembling or characteristic of a fort.",
  "thirteen": "A word meaning: N a 2003 drama film directed by Catherine Hardwicke, written by Hardwicke and Nikki Reed, and starring Holly Hunter, Evan Rachel Wood and Reed...",
  "fifteen": "A word meaning: An Irish traybake made with crushed digestive biscuits, marshmallows and glacé cherries combined with condensed milk and desiccated coconut.",
  "sixteen": "A word meaning: The cardinal number that is the sum of fifteen and one.",
  "appoint": "A word meaning: To name .",
  "english": "A word meaning: Of or pertaining to England.",
  "polite": "A word meaning: Well-mannered, civilized.",
  "chicken": "A word meaning: A domesticated subspecies of red junglefowl .",
  "discuss": "A word meaning: To converse or debate concerning a particular topic.",
  "peanut": "A word meaning: A legume resembling a nut, the fruit of the plant Arachis hypogaea, native to South America.",
  "arithmetic": "A word meaning: The mathematics of numbers under the operations of addition, subtraction, multiplication, and division.",
  "elephant": "A word meaning: A large mammal of the family Elephantidae in the order Proboscidea, having a trunk, and native to Africa and Asia.",
  "demand": "A word meaning: The desire to purchase goods and services.",
  "half": "A word meaning: One of two usually roughly equal parts into which anything may be divided, or considered as divided.",
  "soccer": "A word meaning: Association football.",
  "island": "A word meaning: A contiguous area of land, smaller than a continent, totally surrounded by water.",
  "request": "A word meaning: To ask for .",
  "minus": "A word meaning: The this word sign .",
  "backpack": "A word meaning: A knapsack, sometimes mounted on a light frame, but always supported by straps, worn on a person’s back for the purpose of carrying things.",
  "gorilla": "A word meaning: An ape of the genus this word; endemic to the forests of Central Africa and typified by superlative physical size and strength in relation to...",
  "relief": "A word meaning: The removal of stress or discomfort.",
  "plus": "A word meaning: A positive quantity.",
  "decided": "A word meaning: Determined; resolute.",
  "dolphin": "A word meaning: A carnivorous aquatic mammal in one of several families of the infraorder Cetacea, famed for its intelligence and occasional willingness to...",
  "percent": "A word meaning: For every hundred .",
  "machine": "A word meaning: A device that directs and controls energy, often in the form of movement or electricity, to produce a certain effect.",
  "contain": "A word meaning: To hold inside.",
  "structure": "A word meaning: A cohesive whole built up of distinct parts.",
  "signature": "A word meaning: A person's name, written by that person, used as identification or to signify approval of accompanying material, such as a legal contract.",
  "quarter": "A word meaning: A fourth part of something.",
  "course": "A word meaning: A sequence of events.",
  "finally": "A word meaning: At the end or conclusion; ultimately.",
  "furniture": "A word meaning: Large movable item, usually in a room, which enhance the room's characteristics, functionally or decoratively.",
  "surface": "A word meaning: The overside or up-side of a flat object such as a table, or of a liquid.",
  "ticket": "A word meaning: A small document that acts as proof of something, often thereby granting the holder some ability.",
  "diet": "A word meaning: The food and beverage a person or animal consumes.",
  "zero": "A word meaning: The numeric symbol that represents the cardinal number this word.",
  "departure": "A word meaning: The act of departing or something that has departed.",
  "produce": "A word meaning: To bring forth, to yield, make, manufacture, or otherwise generate.",
  "puppet": "A word meaning: Any small model of a person or animal able to be moved by strings or rods, or in the form of a glove.",
  "capture": "A word meaning: To take control of; to seize by force or stratagem.",
  "fresher": "A word meaning: A first-year student at a university.",
  "stretcher": "A word meaning: A simple litter designed to carry a sick, injured, or dead person.",
  "culture": "A word meaning: The arts, customs, lifestyles, background, and habits that characterize humankind, or a particular society or nation.",
  "banquet": "A word meaning: A large celebratory meal; a feast.",
  "usher": "A word meaning: A person, in a church, cinema etc., who escorts people to their seats.",
  "blanket": "A word meaning: A heavy, loosely woven fabric, usually large and woollen, used for warmth while sleeping or resting.",
  "preacher": "A word meaning: Someone who preaches a worldview, philosophy, or religion.",
  "gadget": "A word meaning: Any device or machine, especially one whose name cannot be recalled, often either clever or complicated.",
  "gusher": "A word meaning: An oil well that has a natural flow and so requires no pumping.",
  "pressure": "A word meaning: A pressing; a force applied to a surface.",
  "creature": "A word meaning: A living being, such as an animal, monster, or alien.",
  "fixture": "A word meaning: Something that is fixed in place, especially a permanent appliance or other item of personal property that is considered part of a house and is...",
  "crusher": "A word meaning: Someone or something that crushes.",
  "closure": "A word meaning: An event or occurrence that signifies an ending.",
  "musket": "A word meaning: A kind of firearm formerly carried by the infantry of an army.",
  "flasher": "A word meaning: An indicator or turn signal.",
  "fracture": "A word meaning: A break in bone or cartilage.",
  "poet": "A word meaning: A person who writes poems.",
  "treasure": "A word meaning: A collection of valuable things; accumulated wealth; a stock of money, jewels, etc.",
  "species": "A word meaning: A group of sexually reproducing organisms of which any two individuals of the appropriate sexes or mating types can produce fertile offspring,...",
  "pioneer": "A word meaning: A person or other entity who is first or among the earliest in any field of inquiry, enterprise, or progress.",
  "squatter": "A word meaning: One who occupies a building or land without title or permission.",
  "agriculture": "A word meaning: The art or science of cultivating the ground, including the growing and harvesting of crops, and the rearing and management of livestock.",
  "balanced": "A word meaning: Containing elements in appropriate proportion.",
  "competition": "A word meaning: The action of competing.",
  "immigrate": "A word meaning: To move into a foreign country to stay permanently.",
  "strike": "A word meaning: To delete or cross out; to scratch or eliminate.",
  "migrate": "A word meaning: To relocate periodically from one region to another, usually according to the seasons.",
  "architecture": "A word meaning: The art and science of designing and managing the construction of buildings and other structures.",
  "exclusion": "A word meaning: The act of excluding or shutting out; removal from consideration or taking part.",
  "interdependence": "A word meaning: The condition of being interdependent.",
  "hypothesis": "A word meaning: A tentative conjecture explaining an observation, phenomenon or scientific problem and that can be tested by further observation, investigation,...",
  "algebraic": "A word meaning: Of, or relating to, algebra.",
  "watt": "A word meaning: In the International System of Units, the derived unit of power.",
  "density": "A word meaning: A measure of the mass of matter contained by a unit volume.",
  "endangered": "A word meaning: In danger, at risk, said of something where there is a strong possibility something bad will happen to it.",
  "expression": "A word meaning: The action of expressing thoughts, ideas, feelings, etc.",
  "fluorescent": "A word meaning: Exhibiting or produced by fluorescence.",
  "algorithm": "A word meaning: A collection of ordered steps that solve a mathematical problem.",
  "extinction": "A word meaning: The action of making or becoming extinct; annihilation.",
  "circuit": "A word meaning: Enclosed path of an electric current, usually designed for a certain function.",
  "slide": "A word meaning: To move in continuous contact with a surface.",
  "parentheses": "A word meaning: A clause, phrase or word which is inserted into a passage which is already grammatically complete, and usually marked off with brackets, commas or...",
  "building": "A word meaning: A closed structure with walls and a roof.",
  "sixty": "A word meaning: A commercial lasting 60 seconds.",
  "plenty": "A word meaning: A more-than-adequate amount; plenitude.",
  "fourteen": "A word meaning: Being one more than thirteen.",
  "swings": "A word meaning: To ride on a this word.",
  "spelling": "A word meaning: The act, practice, ability, or subject of forming words with letters, or of reading the letters of words.",
  "system": "A word meaning: A group or set of related things that operate together as a complex whole.",
  "relax": "A word meaning: To rest and become relieved of stress.",
  "class": "A word meaning: A group, collection, category or set sharing characteristics or attributes.",
  "figure": "A word meaning: A drawing or diagram conveying information.",
  "buffalo": "A word meaning: An animal from the subtribe Bubalina, also known as true buffalos, such as the Cape this word, Syncerus caffer, or the water this word, Bubalus...",
  "monkey": "A word meaning: A member of the clade Simiiformes other than those in the clade Hominoidea containing apes, generally distinguished by small size, tails, and...",
  "determine": "A word meaning: To ascertain definitely; to figure out, find out, or conclude by analyzing, calculating, or investigating.",
  "became": "A word meaning: Begin to be; turn into .",
  "fifty": "A word meaning: A banknote or coin with a denomination of 50.",
  "nothing": "A word meaning: Something trifling, or of no consequence or importance.",
  "alligator": "A word meaning: Either of two species of large amphibious reptile, this word mississippiensis or this word sinensis, in the genus this word within order...",
  "field": "A word meaning: A land area free of woodland, cities, and towns.",
  "shown": "A word meaning: A surname.",
  "revise": "A word meaning: To review, alter and amend, especially of written material.",
  "travel": "A word meaning: To be on a journey, often for pleasure or business and with luggage.",
  "minutes": "A word meaning: The official notes kept during a meeting.",
  "wolves": "A word meaning: The city of Wolverhampton, England.",
  "carefully": "A word meaning: With care; attentively, circumspectly.",
  "pasture": "A word meaning: Land, specifically, an open field, on which livestock is kept for feeding.",
  "force": "A word meaning: Ability to influence; strength or energy of body or mind; active power; vigour; might; capacity of exercising an influence or producing an effect.",
  "kangaroo": "A word meaning: A member of the Macropodidae family of large marsupials with strong hind legs for hopping, native to Australia.",
  "scientists": "A word meaning: One whose activities make use of the scientific method to answer questions regarding the measurable universe.",
  "sketch": "A word meaning: To make a brief, basic drawing.",
  "adventure": "A word meaning: A feeling of desire for new and exciting things.",
  "inside": "A word meaning: The interior or inner part.",
  "brought": "A word meaning: To transport toward somebody/somewhere.",
  "rancher": "A word meaning: A person who operates a ranch.",
  "wheels": "A word meaning: An automobile or other vehicle; a set of this word.",
  "literature": "A word meaning: The body of all written works.",
  "lecture": "A word meaning: A spoken lesson or exposition, usually delivered to a group.",
  "leisure": "A word meaning: Free time, time free from work or duties.",
  "bleacher": "A word meaning: A stand of tiered planks used as seating for spectators, often outdoors.",
  "understand": "A word meaning: To know the meaning of; to parse or have parsed correctly; to comprehend.",
  "audit": "A word meaning: An independent review and examination of records and activities to assess the adequacy of system controls, to ensure compliance with established...",
  "richer": "A word meaning: A surname.",
  "seizure": "A word meaning: A sudden attack or convulsion, .",
  "credit": "A word meaning: Reliance on the truth of something said or done.",
  "mixture": "A word meaning: Something produced by mixing.",
  "voucher": "A word meaning: A piece of paper or other token that entitles the holder to a discount, or that can be exchanged for goods and services.",
  "moisture": "A word meaning: The state of being moist.",
  "pleasure": "A word meaning: A state of being pleased or contented; gratification.",
  "pitcher": "A word meaning: The player who delivers the ball to the batter.",
  "puncture": "A word meaning: A hole in a vehicle's tyre, causing the tyre to deflate.",
  "vomit": "A word meaning: To regurgitate or eject the contents of the stomach through the mouth.",
  "vulture": "A word meaning: Any of several carrion-eating birds of the families Accipitridae and Cathartidae.",
  "hermit": "A word meaning: A recluse; someone who lives alone and shuns human companionship.",
  "catcher": "A word meaning: The player who squats behind home plate and receives the pitches from the pitcher.",
  "sculpture": "A word meaning: A three-dimensional work of art created by shaping malleable objects and letting them harden or by chipping away pieces from a rock .",
  "rupture": "A word meaning: A burst, split, or break.",
  "habit": "A word meaning: An action performed on a regular basis.",
  "urban": "A word meaning: Of, pertaining to, characteristic of, or happening or located in, a city or town.",
  "erratic": "A word meaning: Unsteady, random; prone to unexpected changes; not consistent.",
  "bandit": "A word meaning: One who robs others in a lawless area, especially as part of a group.",
  "carnivore": "A word meaning: An organism that feeds chiefly on animals.",
  "suburban": "A word meaning: Relating to or characteristic of or situated on the outskirts of a city.",
  "moraine": "A word meaning: An accumulation of rocks and debris carried and deposited by a glacier.",
  "herbivore": "A word meaning: An organism that feeds chiefly on plants; an animal that feeds on herbage or vegetation as the main part of its diet.",
  "rural": "A word meaning: Relating to the countryside or to agriculture.",
  "electrician": "A word meaning: A tradesperson who installs, repairs and maintains electrical wiring and equipment.",
  "omnivore": "A word meaning: An animal which is able to consume both plants and meat .",
  "cirque": "A word meaning: A curved depression or natural amphitheatre.",
  "mathematics": "A word meaning: An abstract representational system studying numbers, shapes, structures, quantitative change and relationships between them.",
  "estimation": "A word meaning: The process of making an estimate.",
  "photosynthesis": "A word meaning: Principally, oxygenic this word, any process by which plants and algae convert water and carbon dioxide into carbohydrates and waste oxygen using...",
  "monolith": "A word meaning: Anything massive, uniform, and unmovable, especially a towering and impersonal cultural, political, or social organization or structure.",
  "mathematician": "A word meaning: An expert on mathematics; someone who studies mathematics.",
  "echolocation": "A word meaning: The use of echoes to detect objects as observed in bats and other natural creatures.",
  "evaluate": "A word meaning: To draw conclusions from examining; to assess; to appraise.",
  "approximate": "A word meaning: Nearing correctness; nearly exact; not perfectly accurate.",
  "renewable": "A word meaning: Sustainable; able to be regrown or renewed; having an ongoing or continuous source of supply.",
  "reasonable": "A word meaning: Not excessive or immoderate; within due limits; proper.",
  "ultrasound": "A word meaning: Medical ultrasonography.",
  "solution": "A word meaning: An act, plan or other means, used or proposed, to solve a problem.",
  "nonrenewable": "A word meaning: Unsustainable; not able to be regrown or renewed; not having an ongoing or continuous source of supply.",
  "seventeen": "A word meaning: N an American bimonthly teen magazine headquartered in New York City.",
  "region": "A word meaning: Any considerable and connected part of a space or surface.",
  "positive": "A word meaning: Included, present, characterized by affirmation.",
  "browser": "A word meaning: Any other type of information this word.",
  "castle": "A word meaning: A large residential building or compound that is fortified and contains many defences.",
  "knight": "A word meaning: A person on whom a knighthood has been conferred by a monarch.",
  "object": "A word meaning: A thing that has physical existence but is not alive.",
  "memory": "A word meaning: The ability of the brain to record information or impressions with the facility of recalling them later, usually at will.",
  "negative": "A word meaning: Not positive or neutral; bad; undesirable; unfavourable.",
  "square": "A word meaning: A polygon with four straight sides of equal length and four right angles.",
  "believe": "A word meaning: To accept as true, particularly without absolute certainty .",
  "explain": "A word meaning: To make plain, manifest, or intelligible; to clear of obscurity; to illustrate the meaning of.",
  "syllables": "A word meaning: A unit of human speech which often forms words corresponding to one opening of the mouth.",
  "joined": "A word meaning: Of or relating to two people who are married to each other.",
  "adage": "A word meaning: An old saying which has obtained credit by long use.",
  "prince": "A word meaning: The ruler or head of a principality.",
  "perhaps": "A word meaning: Possibly.",
  "courage": "A word meaning: The ability to overcome one's fear, do or live things which one finds frightening.",
  "members": "A word meaning: One who belongs to a group.",
  "kingdom": "A word meaning: A realm having a king or queen as its actual or nominal sovereign.",
  "contest": "A word meaning: A competition.",
  "hammer": "A word meaning: A tool with a heavy head and a handle used for pounding.",
  "alone": "A word meaning: By oneself, solitary.",
  "language": "A word meaning: A body of words, and set of methods of combining them , understood by a community and used as a form of communication.",
  "nail": "A word meaning: The thin, horny plate at the ends of fingers and toes on humans and some other animals.",
  "reject": "A word meaning: To refuse to accept; to forswear.",
  "luggage": "A word meaning: The bags and other containers that hold a traveller's belongings.",
  "ghost": "A word meaning: A disembodied soul; a soul or spirit of a deceased person; a spirit appearing after death.",
  "cells": "A word meaning: N a monthly peer-reviewed open-access scientific journal that covers all aspects of this word and molecular biology, and biophysics.",
  "robot": "A word meaning: A machine built to carry out some complex task or group of tasks by physically moving.",
  "storage": "A word meaning: The act of storing goods; the state of being stored.",
  "suddenly": "A word meaning: Happening quickly and with little or no warning.",
  "universe": "A word meaning: The sum of everything that exists in the cosmos.",
  "program": "A word meaning: A computer this word.",
  "wrench": "A word meaning: A movement that twists or pulls violently.",
  "thousands": "A word meaning: N 1000 or one this word is the natural number following 999 and preceding 1001.",
  "computer": "A word meaning: A programmable electronic device that performs mathematical calculations and logical operations.",
  "bandage": "A word meaning: A strip of gauze or similar material used to protect or support a wound or injury.",
  "adopt": "A word meaning: To take by choice into a relationship.",
  "compose": "A word meaning: To construct by mental labor; to think up; particularly, to produce or create a literary or musical work.",
  "abuse": "A word meaning: Improper treatment or usage; application to a wrong or bad purpose; an unjust, corrupt or wrongful practice or custom.",
  "bother": "A word meaning: To annoy, to disturb, to irritate; to be troublesome to, to make trouble for.",
  "coastal": "A word meaning: Relating to the coast; on or near the coast; longshore.",
  "cabbage": "A word meaning: An edible plant having a head of green leaves.",
  "lukewarm": "A word meaning: Unenthusiastic .",
  "soapy": "A word meaning: Resembling soap.",
  "carriage": "A word meaning: The act of conveying; carrying.",
  "congress": "A word meaning: A legislative body of a state, originally the bicameral legislature of the United States of America.",
  "salute": "A word meaning: An utterance or gesture expressing greeting or honor towards someone, a formal, non-verbal gesture made with the arms or hands in any of various...",
  "damage": "A word meaning: Injury or harm; the condition or measure of something not being intact.",
  "comment": "A word meaning: A spoken or written remark.",
  "toaster": "A word meaning: An electrical device for toasting food, typically sliced bread.",
  "rumor": "A word meaning: A statement or claim of questionable accuracy, from no known reliable source, usually spread by word of mouth.",
  "owner": "A word meaning: One who owns something.",
  "garbage": "A word meaning: Useless or disposable material; waste material of any kind.",
  "monster": "A word meaning: A terrifying and dangerous creature, especially one of an imaginary or mythical kind.",
  "tutor": "A word meaning: One who teaches another in a one-on-one or small-group interaction.",
  "reservoir": "A word meaning: A large natural or artificial lake used as a source of water supply.",
  "entrepreneur": "A word meaning: A person who sets up a business; generally, a person who owns and manages a business and assumes its financial risks.",
  "parallel": "A word meaning: Equally distant from one another at all points.",
  "actor": "A word meaning: A person who acts a part in a theatrical play or in film or television.",
  "delta": "A word meaning: A landform at the mouth of a river where it empties into a body of water.",
  "series": "A word meaning: A number of things that follow on one after the other or are connected one after the other.",
  "boomtown": "A word meaning: Alternative form of boom town. [A town that is experiencing or has experienced a period of rapid growth due to some temporary activity.].",
  "bay": "A word meaning: A body of water contained by a concave shoreline.",
  "charge": "A word meaning: The amount of money levied for a service.",
  "magnetic": "A word meaning: Having the properties of a magnet, especially the ability to draw or pull.",
  "compromise": "A word meaning: The settlement of differences by arbitration or by consent reached by mutual concessions.",
  "poles": "A word meaning: Originally, a stick; now specifically, a long and slender piece of metal or wood, used for various construction or support purposes.",
  "college": "A word meaning: An institution of higher education teaching undergraduates.",
  "seventy": "The number after sixty-nine.",
  "solo": "Done by one person alone.",
  "export": "A word meaning: The act of exporting.",
  "petition": "A word meaning: A formal written request made by an individual or a group of people to a sovereign or political authority, often containing many signatures,...",
  "permanent": "A word meaning: Lasting for an indefinitely long time.",
  "slavery": "A word meaning: An institution or social practice of owning human beings as property.",
  "university": "A word meaning: An institution of higher education that provides facilities for teaching, research, and the conferral of academic degrees across undergraduate,...",
  "sheriff": "A law officer in a town or county.",
  "import": "A word meaning: To bring in from a foreign country, especially for sale or trade.",
  "temporary": "A word meaning: Not permanent; existing only for a period or periods of time.",
  "degree": "A word meaning: A stage of proficiency or qualification in a course of study.",
  "fugitive": "A word meaning: A person who flees or escapes and travels secretly from place to place, and sometimes using disguises and aliases to conceal their identity, as to...",
  "transport": "A word meaning: To carry or bear from one place to another.",
  "appliance": "A word meaning: A non-manual apparatus or device, powered electrically or by another small motor, used in homes to perform domestic functions and/or in offices.",
  "hotel": "A word meaning: An establishment that provides accommodation and other services for paying guests.",
  "eighty": "A word meaning: The cardinal number that is the product of ten and eight.",
  "rhombus": "A word meaning: A parallelogram having all sides of equal length.",
  "duet": "A word meaning: A song composed for and/or performed by a duo.",
  "guest": "A word meaning: A recipient of hospitality, especially someone staying by invitation at the house of another.",
  "equation": "A word meaning: An assertion that two expressions are equal, expressed by writing the two expressions separated by an equal sign.",
  "material": "A word meaning: Of, relating to, or consisting of matter, especially physical.",
  "rodeo": "A word meaning: A North American sport involving skills with horses, cows and other livestock.",
  "ready": "A word meaning: Prepared for immediate action or use.",
  "special": "A word meaning: Distinguished by a unique, particular, or unusual quality.",
  "average": "A word meaning: Any measure of central tendency, especially any mean, the median, or the mode.",
  "anything": "A word meaning: In any way, any extent or any degree.",
  "exercise": "A word meaning: Activity intended to improve physical, or sometimes mental, strength and fitness.",
  "heavy": "A word meaning: Having great weight.",
  "government": "A word meaning: The body with the power to make and/or enforce laws to control a country, land area, people or organization.",
  "wagon": "A word meaning: A heavier four-wheeled vehicle designed to carry goods .",
  "filled": "A word meaning: That is now full.",
  "elevator": "A word meaning: A permanent construction with a built-in platform or cab that can be raised and lowered, used to transport people and goods, as between different...",
  "trio": "A word meaning: A group of three people or things.",
  "pledge": "A word meaning: To make a solemn promise .",
  "generalize": "A word meaning: To infer or induce from specific cases to more general cases or principles.",
  "choir": "A word meaning: A group of people who sing together; a company of people who are trained to sing together.",
  "energy": "A word meaning: The capacity to do work.",
  "bridge": "A word meaning: A construction or natural feature that spans a divide.",
  "railroad": "A word meaning: A permanent track consisting of fixed metal rails to drive trains or similar motorized vehicles on.",
  "axe": "A word meaning: A tool for felling trees or chopping wood etc.",
  "subject": "A word meaning: The main topic of a paper, work of art, discussion, field of study, etc.",
  "saddle": "A word meaning: A seat for a rider, typically made of leather and raised in the front and rear, placed on the back of a horse or other animal, and secured by a...",
  "include": "A word meaning: To bring into a group, class, set, or total as a part or member.",
  "ridge": "A word meaning: Any extended protuberance; a projecting line or strip.",
  "europe": "A word meaning: A continent located west of Asia , north of Africa and east of the Atlantic Ocean.",
  "calf": "A word meaning: A young cow or bull of any bovid, such as domestic cattle or buffalo.",
  "wedge": "A word meaning: One of the simple machines; a piece of material, such as metal or wood, thick at one edge and tapered to a thin edge at the other for insertion in...",
  "homework": "A word meaning: Exercises assigned by a teacher to a student which review concepts studied in class.",
  "umbrella": "A word meaning: A cloth-covered frame used for protection against rain or sun.",
  "ledge": "A word meaning: A narrow surface projecting horizontally from a wall, cliff, or other surface.",
  "developed": "A word meaning: Wealthy and industrialized; not third-world.",
  "lower": "A word meaning: Bottom; more towards the bottom than the middle of an object.",
  "bubble": "A word meaning: A spherically contained volume of air or other gas.",
  "alarm": "A word meaning: Any sound or information intended to give notice of approaching danger.",
  "bony": "A word meaning: With little flesh; skinny, thin.",
  "husband": "A word meaning: A man in a marriage or marital relationship.",
  "carbon": "A word meaning: The chemical element with an atomic number of 6.",
  "cartridge": "A word meaning: The package consisting of the bullet, primer, and casing containing gunpowder.",
  "partridge": "A word meaning: Any bird of a number of genera in the family Phasianidae, notably in the genera Perdix and Alectoris.",
  "bucket": "A word meaning: A container made of rigid material, often with a handle, used to carry liquids or small items.",
  "stroller": "A word meaning: A seat or chair on wheels, pushed by somebody walking behind it, typically used for transporting babies and young children.",
  "porridge": "A word meaning: A dish made of grain or legumes, milk or water, heated and stirred until thick and typically eaten for breakfast.",
  "charcoal": "A word meaning: Impure carbon obtained by destructive distillation of wood or other organic matter, that is, heating it in the absence of oxygen.",
  "decode": "A word meaning: To convert from an encrypted form to plain text.",
  "publish": "A word meaning: To issue for distribution and/or sale.",
  "marble": "A word meaning: A metamorphic rock of crystalline limestone.",
  "molten": "A word meaning: Melted, especially due to great heat.",
  "knowledge": "A word meaning: The fact of knowing about something; general understanding or familiarity with a subject, place, situation etc.",
  "snuggle": "A word meaning: To lie close to another person or thing, hugging or being cosy.",
  "scarlet": "A word meaning: A brilliant red colour sometimes tinged with orange.",
  "navigation": "A word meaning: The theory, practice and technology of charting a course for a road vehicle, ship, aircraft, or spaceship.",
  "engineer": "A word meaning: A person professionally engaged in the technical design and construction of large-scale private and public works such as bridges, buildings,...",
  "inflation": "A word meaning: An increase in the quantity of money, leading to a devaluation of existing money, adjusted for by way of higher nominal values.",
  "aurora": "A word meaning: An atmospheric phenomenon created by charged particles from the sun striking the upper atmosphere, creating coloured lights in the sky.",
  "ration": "A word meaning: A portion of some limited resource, especially food, allocated to a person or group.",
  "circumnavigate": "A word meaning: To travel completely around somewhere or something.",
  "technology": "A word meaning: Any useful skill or mechanism that humans have developed or invented .",
  "quadrant": "A word meaning: One of the four regions of the Cartesian plane bounded by the x-axis and y-axis.",
  "globe": "A word meaning: The planet Earth.",
  "stock": "A word meaning: A store or supply.",
  "ordered": "A word meaning: In this word, not messy, tidy.",
  "public": "A word meaning: Able to be known or seen by everyone; happening without concealment; open to general view.",
  "electricity": "A word meaning: Electrical power, as supplied by power stations or generators.",
  "conductor": "A word meaning: A person who conducts an orchestra, choir or other music ensemble.",
  "coordinates": "A word meaning: N the fourth extended play by Swedish pop boy band The Fooo Conspiracy.",
  "private": "A word meaning: Belonging or pertaining to an individual person, group of people, or entity that is not the state.",
  "depression": "A word meaning: A state of mind producing serious, long-term lowering of enjoyment of life or inability to visualize a happy future.",
  "drought": "A word meaning: A period of unusually low rainfall, longer and more severe than a dry spell.",
  "insulator": "A word meaning: A substance that does not transmit heat , sound or electricity .",
  "grid": "A word meaning: A system for delivery of electricity, consisting of various substations, transformers and generators, connected by wire.",
  "static": "A word meaning: Unchanging; that cannot or does not change.",
  "academic": "A word meaning: Belonging to an academy or other higher institution of learning, or a scholarly society or organization.",
  "aqueduct": "A word meaning: An artificial channel that is constructed to convey water from one location to another.",
  "window": "A word meaning: An opening, usually covered by one or more panes of clear glass, to allow light and air from outside to enter a building or vehicle.",
  "segment": "A word meaning: One of the parts into which any body naturally separates or is divided.",
  "kitchen": "A word meaning: A room or area for preparing food.",
  "actress": "A word meaning: A female who performs on the stage or in films.",
  "nineteen": "A word meaning: Being one more than eighteen.",
  "score": "A word meaning: The total number of goals, points, runs, etc.",
  "dining": "A word meaning: Eating dinner as a social function.",
  "difference": "A word meaning: The quality of being different.",
  "theatre": "A word meaning: A cinema; movie this word.",
  "cousin": "A word meaning: When used without a qualifying word: the child of a person's parent's brother or sister.",
  "pantry": "A word meaning: A small room, closet, or cabinet usually located in or near the kitchen, dedicated to shelf-stable food storage or storing kitchenware, like a...",
  "eighteen": "A word meaning: A surname.",
  "solve": "A word meaning: To find an answer or solution to a problem or question.",
  "heart": "A word meaning: A muscular organ that pumps blood through the body, traditionally thought to be the seat of emotion.",
  "present": "A word meaning: Relating to now, for the time being; current.",
  "appear": "A word meaning: To come or be in sight; to be in view; to become visible.",
  "site": "A word meaning: A website.",
  "staircase": "A word meaning: A flight of stairs; a stairway.",
  "beautiful": "A word meaning: Possessing beauty, impressing the eye; attractive.",
  "metal": "A word meaning: Any of a number of chemical elements in the periodic table that form a metallic bond with other this word atoms.",
  "instruments": "A word meaning: A device used to produce music.",
  "charm": "A word meaning: The ability to persuade, delight or arouse admiration.",
  "burning": "A word meaning: On fire.",
  "ornament": "A word meaning: An element of decoration; that which embellishes or adorns.",
  "dramatic": "A word meaning: Of or relating to the drama.",
  "corner": "A word meaning: The point where two converging lines meet.",
  "format": "A word meaning: The layout of a publication or document.",
  "either": "A word meaning: As well.",
  "shoreline": "A word meaning: The divide between land and a body of water.",
  "harmfully": "A word meaning: In a harmful manner.",
  "portrait": "A word meaning: A painting or other picture of a person, especially the head and shoulders.",
  "storm": "A word meaning: Any disturbed state of the atmosphere causing destructive or unpleasant weather.",
  "neither": "A word meaning: Similarly not.",
  "merge": "A word meaning: To combine into a whole.",
  "afford": "A word meaning: To incur, stand, or bear without serious detriment, as an act which might under other circumstances be injurious.",
  "curtain": "A word meaning: A piece of cloth covering a window, bed, etc.",
  "goose": "A word meaning: Any of various grazing waterfowl of the family Anatidae, which have feathers and webbed feet and are capable of flying, swimming, and walking on...",
  "probably": "A word meaning: In all likelihood.",
  "squirt": "A word meaning: An instrument from which a liquid is forcefully ejected in a small, quick stream.",
  "raised": "A word meaning: Leavened, especially with yeast.",
  "parsley": "A word meaning: The leaves of this plant used in Middle Eastern, European, and American cooking.",
  "sermon": "A word meaning: Religious discourse; a written or spoken address on a religious or moral matter.",
  "burden": "A word meaning: A heavy load.",
  "aloof": "A word meaning: Reserved and remote; either physically or emotionally distant; standoffish.",
  "village": "A word meaning: A rural habitation of size between a hamlet and a town.",
  "tardy": "A word meaning: Late; overdue or delayed.",
  "purchase": "A word meaning: The acquisition of title to, or property in, anything for a price.",
  "moody": "A word meaning: Given to sudden or frequent changes of mind.",
  "verdict": "A word meaning: A decision on an issue of fact in a civil or criminal case or an inquest.",
  "tariff": "A word meaning: A system of government-imposed duties levied on imported or exported goods.",
  "bleary": "A word meaning: Tired, having senses dulled by exhaustion.",
  "plural": "A word meaning: Consisting of or containing more than one of something.",
  "raccoon": "A word meaning: An omnivorous, nocturnal mammal native to the Americas, of the genus Procyon, typically with a mixture of gray, brown, and black fur, a mask-like...",
  "prairie": "A word meaning: An extensive area of relatively flat grassland with few, if any, trees.",
  "surgeon": "A word meaning: One who performs surgery; a doctor who performs operations on people or animals.",
  "earthworm": "A word meaning: A worm that lives in the ground.",
  "askew": "A word meaning: Turned or twisted to one side.",
  "barrel": "A word meaning: A round vessel, such as a cask, of greater length than breadth, and bulging in the middle, made of staves bound with hoops, and having flat ends.",
  "learning": "A word meaning: An act in which something is learned.",
  "ray": "A word meaning: A beam of light or radiation.",
  "endure": "A word meaning: To continue or carry on, despite obstacles or hardships.",
  "angle": "A word meaning: A figure formed by two rays which start from a common point or by three planes that intersect .",
  "jewel": "A word meaning: A valuable object used for personal ornamentation.",
  "executive": "A word meaning: Of, pertaining to, or having responsibility for the day-to-day running of an organisation, business, country, etc.",
  "moose": "A word meaning: The largest member of the deer family , of which the male has very large, palmate antlers.",
  "obtuse": "A word meaning: Intellectually dull or dim-witted.",
  "dimension": "A word meaning: A measure of spatial extent in a particular direction, such as height, width or breadth, or depth.",
  "judicial": "A word meaning: Of or relating to the administration of justice.",
  "perpendicular": "A word meaning: At or forming a right angle .",
  "ounce": "A word meaning: An avoirdupois this word, weighing ¹⁄₁₆ of an avoirdupois pound, or 28.349523125 grams.",
  "acute": "A word meaning: Intense; sensitive; sharp.",
  "legislative": "A word meaning: Making, or having the power to make, a law or laws.",
  "branch": "A word meaning: The woody part of a tree arising from the trunk and usually dividing.",
  "protractor": "A word meaning: A circular or semicircular tool for drawing or measuring angles.",
  "millimeter": "A word meaning: US spelling of millimetre. [An SI/MKS unit of measure, the length of ¹⁄₁₀₀₀ of a metre. Symbol: mm].",
  "vertex": "A word meaning: An angular point of a polygon, polyhedron or higher order polytope.",
  "professional": "A word meaning: A person who belongs to a profession.",
  "intersecting": "A word meaning: Crossed or intersected in the form of an x.",
  "quadrilateral": "A word meaning: A polygon with four sides.",
  "jurisdiction": "A word meaning: The power, right, or authority to interpret and apply the law.",
  "hexagon": "A word meaning: A polygon with six sides and six angles.",
  "centimeter": "A word meaning: Alternative form of centimetre.",
  "congruent": "A word meaning: Having a difference divisible by a modulus.",
  "district": "A word meaning: An administrative division of an area.",
  "kilometer": "A word meaning: US spelling of kilometre. [ An SI unit of length equal to 10³ metres. Symbol: km].",
  "ninety": "A word meaning: Being ten more than eighty.",
  "forward": "A word meaning: Situated toward or at the front of something.",
  "factors": "A word meaning: One of the elements, circumstances, or influences which contribute to produce a result.",
  "represent": "A word meaning: To stand or act in the place of; to perform the duties, exercise the rights, or otherwise act on behalf of.",
  "principal": "A word meaning: Primary; most important; first level in importance.",
  "finished": "A word meaning: Completed; concluded; done.",
  "reply": "A word meaning: To give a written or spoken response, especially to a question, request, accusation or criticism.",
  "result": "A word meaning: That which results; the conclusion or end to which any course or condition of things leads, or which is obtained by any process or operation;...",
  "purple": "A word meaning: A colour between red and blue; violet, though often closer to magenta.",
  "discovered": "A word meaning: No longer concealed; uncovered as by opening a curtain; `this word' is archaic and primarily a theater term.",
  "whether": "A word meaning: The retention of the afterbirth in cows or sheep.",
  "camera": "A word meaning: A device for taking still or moving pictures or photographs.",
  "chord": "A word meaning: A harmonic set of three or more notes that is heard as if sounding simultaneously.",
  "amuse": "A word meaning: To entertain or occupy in a pleasant manner.",
  "clothes": "A word meaning: Items of clothing; apparel.",
  "video": "A word meaning: Television, a television show, or a movie.",
  "porch": "A word meaning: A covered entrance to a building, whether taken from the interior, and forming a sort of vestibule within the main wall, or projecting without and...",
  "allowance": "A word meaning: An amount, portion, or share that is allotted or granted.",
  "flowers": "A word meaning: A surname.",
  "image": "A word meaning: A visual or other representation of the external form of something in art.",
  "written": "A word meaning: Having been this word.",
  "beside": "A word meaning: Otherwise; else; in addition; besides.",
  "scan": "A word meaning: To examine sequentially, carefully, or critically.",
  "frame": "A word meaning: To fit, as for a specific end or purpose; make suitable or comfortable; adapt; adjust.",
  "purpose": "A word meaning: The end for which something is done, is made or exists.",
  "concern": "A word meaning: That which affects one’s welfare or happiness.",
  "delete": "A word meaning: To remove, get rid of or erase, especially written or printed material, or data on a computer or other device.",
  "movies": "A word meaning: The cinema.",
  "reason": "A word meaning: Rational thinking ; the cognitive faculties, collectively, of conception, judgment, deduction and intuition.",
  "thorn": "A word meaning: A modified branch that is hard and sharp like a spike.",
  "address": "A word meaning: Direction.",
  "zoom": "A word meaning: A humming noise from something moving very fast.",
  "kept": "A word meaning: N a reality television series that centered on Jerry Hall searching for a this word man.",
  "sword": "A word meaning: A long bladed weapon with a grip and typically a pommel and crossguard , which is designed to cut, stab, slash and/or hack.",
  "cookies": "A word meaning: N a music group in Hong Kong created by Chan Chi Kwong under the giant record label EMI Hong Kong and later managed by Paco Wong of then Gold...",
  "stern": "A word meaning: Having a hardness and severity of nature or manner.",
  "million": "A word meaning: Denoting a quantity consisting of 1,000,000 items or units.",
  "interest": "A word meaning: A great attention and concern from someone or something.",
  "berry": "A word meaning: A small succulent fruit, of any one of many varieties.",
  "neighborhood": "A word meaning: The residential area near one's home.",
  "describe": "A word meaning: To represent in words.",
  "mature": "A word meaning: Fully developed; grown up in terms of physical appearance, behaviour or thinking; ripe.",
  "clearing": "A word meaning: The act or process of making or becoming this word.",
  "flooding": "A word meaning: An act of this word; a this word or gush.",
  "cherub": "A word meaning: In later texts changed to a winged baby; in artistic depictions sometimes a baby's head with wings but no body.",
  "yearly": "A word meaning: Every year.",
  "obscure": "A word meaning: Difficult to understand; abstruse.",
  "merit": "A word meaning: Something deserving or worthy of positive recognition or reward.",
  "surely": "A word meaning: Certainly, undoubtedly.",
  "cookout": "A word meaning: A gathering for a meal that is cooked and eaten outside.",
  "career": "A word meaning: One’s calling in life; one's working occupation or profession.",
  "perish": "A word meaning: To die; to cease to live.",
  "footprint": "A word meaning: The impression of the foot in a soft substance such as sand or snow.",
  "merely": "A word meaning: Without any other reason etc.; only, just, and nothing more.",
  "assure": "A word meaning: To make sure and secure; ensure.",
  "woodland": "A word meaning: Land covered with woody vegetation.",
  "mercy": "A word meaning: Forgiveness or compassion, especially toward those less fortunate.",
  "sincere": "A word meaning: Genuine; meaning what one says or does; heartfelt.",
  "mistook": "A word meaning: An error.",
  "dirty": "A word meaning: Unclean; covered with or containing unpleasant substances such as dirt or grime.",
  "manure": "A word meaning: Animal excrement, especially that of common domestic farm animals and when used as fertilizer.",
  "spooky": "A word meaning: Eerie, or suggestive of ghosts or the supernatural.",
  "translation": "A word meaning: The conversion of text from one language to another.",
  "amendment": "A word meaning: An addition to and/or alteration to the Constitution.",
  "curb": "A word meaning: To check, restrain or control.",
  "principle": "A word meaning: A fundamental assumption or guiding belief.",
  "rotation": "A word meaning: The act of turning around a centre or an axis.",
  "perimeter": "A word meaning: The sum of the distance of all the lengths of the sides of an object.",
  "citizenship": "A word meaning: The state of being a citizen; the status of a citizen.",
  "reflection": "A word meaning: The act of reflecting or the state of being reflected.",
  "radius": "A word meaning: A line segment between any point of a circle or sphere and its center.",
  "irregular": "A word meaning: Nonstandard; not conforming to rules or expectations.",
  "convention": "A word meaning: A practice or procedure widely observed in a group.",
  "diameter": "A word meaning: Any straight line between two points on the circumference of a circle that passes through the centre/center of the circle.",
  "miniature": "A word meaning: A small version of something; a model of reduced scale.",
  "tessellation": "A word meaning: A tiling pattern with no gaps; the result of tessellating an area or plane.",
  "responsibility": "A word meaning: A duty, obligation or liability for which someone is held accountable.",
  "symmetric": "A word meaning: Synonym of symmetrical.",
  "circumference": "A word meaning: The line that bounds a circle or other two-dimensional figure.",
  "artificial": "A word meaning: Man-made; made by humans; of artifice.",
  "election": "A word meaning: A process of choosing a leader, members of parliament, councillors, or other representatives by popular vote.",
  "symmetry": "A word meaning: Exact correspondence on either side of a dividing line, plane, center or axis.",
  "partial": "A word meaning: Existing as a part or portion; incomplete.",
  "parallelogram": "A word meaning: A convex quadrilateral in which each pair of opposite edges are parallel and of equal length.",
  "decade": "A word meaning: A period of ten years , particularly such a period beginning with a year ending in 0 and ending with a year ending in 9.",
  "orange": "A word meaning: Any round citrus fruit with a yellow-red colour when ripe and a sour-sweet taste.",
  "ribbon": "A word meaning: A long, narrow strip of material used for decoration of clothing or the hair or gift wrapping.",
  "century": "A word meaning: A period of one hundred consecutive years.",
  "mirror": "A word meaning: A smooth surface, usually made of glass with reflective material painted on the underside, that reflects light so as to give an image of what is...",
  "temperature": "A word meaning: A measure of cold or heat, often measurable with a thermometer.",
  "banana": "A word meaning: An elongated curved tropical fruit of a this word plant, which grows in bunches and has a creamy flesh and a smooth skin.",
  "quantity": "A word meaning: A fundamental, generic term used when referring to the measurement of a scalar, vector, number of items or to some other way of denominating the...",
  "grapefruit": "A word meaning: The large spherical tart fruit produced by this tree.",
  "breeze": "A word meaning: A light, gentle wind.",
  "amount": "A word meaning: The total, aggregate or sum of material .",
  "everything": "A word meaning: Used as a placeholder verb to encapsulate a set of related verbs or any action.",
  "calm": "A word meaning: Peaceful, quiet, especially free from anger and anxiety.",
  "pineapple": "A word meaning: The ovoid fruit of the this word plant, which has very sweet white or yellow flesh, a tough, spiky shell and a tough, fibrous core.",
  "scale": "A word meaning: An ordered, usually numerical sequence used for measurement.",
  "release": "The distribution, either public or private, of an initial or new and upgraded version of a computer software product.",
  "remove": "A word meaning: To delete.",
  "strawberry": "A word meaning: The sweet, usually red, edible accessory fruit of certain plants of the genus Fragaria.",
  "already": "A word meaning: Prior to some specified time, either past, present, or future.",
  "method": "A word meaning: A process by which a task is completed; a way of doing something .",
  "laughed": "A word meaning: To show mirth, satisfaction, or derision, by peculiar movement of the muscles of the face.",
  "section": "A word meaning: A cutting; a part cut out from the rest of something.",
  "instead": "A word meaning: In the place of something ; as a substitute or alternative.",
  "although": "A word meaning: Despite the fact that.",
  "lemon": "A word meaning: A yellowish citrus fruit.",
  "per": "A word meaning: Belonging to per, their . Gender-neutral third-person singular possessive adjective, coordinate with gendered his and her.",
  "phrase": "A word meaning: A short written or spoken expression.",
  "devotion": "A word meaning: The act or state of devoting or being devoted.",
  "quite": "A word meaning: To the greatest extent or degree; completely, entirely.",
  "infection": "A word meaning: An uncontrolled growth of harmful microorganisms in a host.",
  "broken": "A word meaning: Fragmented; in separate pieces.",
  "distraction": "A word meaning: Something that distracts.",
  "type": "A word meaning: A grouping based on shared characteristics.",
  "within": "A word meaning: In or into the interior; inside.",
  "moment": "A word meaning: A particular point of time; an instant.",
  "completion": "A word meaning: The act or state of being or making something complete.",
  "themselves": "A word meaning: N this word, previously known as Them, is an American hip hop duo based in Oakland, California.",
  "dictionary": "A word meaning: A reference work listing words or names from one or more languages, usually ordered alphabetically, explaining each word's meanings or senses,...",
  "invitation": "A word meaning: The act of inviting; solicitation; the requesting of a person's company.",
  "affection": "A word meaning: A feeling of love or strong attachment.",
  "protection": "A word meaning: The process of keeping safe.",
  "digestion": "A word meaning: The process, in the gastrointestinal tract, by which food is converted into substances that can be used by the body.",
  "adaptation": "A word meaning: The process of adapting something or becoming adapted to a situation.",
  "collection": "A word meaning: A set of items or amount of material procured, gathered or presented together.",
  "reaction": "A word meaning: An action or statement in response to a stimulus or other event.",
  "disruption": "A word meaning: An interruption to the regular flow or sequence of something.",
  "confrontation": "A word meaning: The act of confronting or challenging another.",
  "construction": "A word meaning: The process of constructing.",
  "compassion": "A word meaning: Deep awareness of the suffering of others that people have to the point of them being motivated to relieve such states.",
  "invention": "A word meaning: Something invented.",
  "indentation": "A word meaning: The act of beginning a line or series of lines at a little distance within the flush line of the column or page, as in the common way of beginning...",
  "adoption": "A word meaning: The state of being adopted; the acceptance of a child of other parents as if he or she were one's own child.",
  "fraction": "A word meaning: A part of a whole, especially a comparatively small part.",
  "prevention": "A word meaning: Any measure intended to limit health-related risks .",
  "inspection": "A word meaning: The act of examining something, often closely.",
  "plantation": "A word meaning: A large farm; estate or area of land designated for agricultural growth.",
  "corruption": "A word meaning: Unethical administrative or executive practices , including bribery , conflicts of interest, nepotism, embezzlement, and so on.",
  "suggestion": "A word meaning: Something suggested.",
  "presentation": "A word meaning: The act of presenting, or something presented.",
  "inaccurate": "A word meaning: Mistaken or incorrect; not accurate.",
  "illiterate": "A word meaning: Unable to read and write.",
  "irreconcilable": "A word meaning: Unable to be reconciled; opposed; uncompromising.",
  "immobile": "A word meaning: Fixed, not movable.",
  "inefficient": "A word meaning: Not efficient; not producing the effect intended or desired; inefficacious.",
  "illicit": "A word meaning: Unlawful.",
  "immoral": "A word meaning: Breaching principles of natural law, rectitude, or justice, and so inconsistent with the demands of virtue, purity, or \"good morals\".",
  "irrelevant": "A word meaning: Not relevant, as.",
  "inoperative": "A word meaning: Not working or functioning; either idle or broken.",
  "illogical": "A word meaning: Contrary to logic; lacking sense or sound reasoning.",
  "immovable": "A word meaning: Incapable of being physically moved; fixed.",
  "irreversible": "A word meaning: Incapable of being reversed or turned about or back.",
  "illustrate": "A word meaning: To clarify something by giving, or serving as, an example or a comparison.",
  "insecure": "A word meaning: Not comfortable or confident in oneself or in certain situations.",
  "ecology": "A word meaning: The branch of biology dealing with the relationships of organisms with their environment and with each other.",
  "illegal": "A word meaning: Contrary to, forbidden, or not authorized by law.",
  "irritate": "A word meaning: To provoke impatience, anger, or displeasure in.",
  "immature": "A word meaning: Childish in behavior; juvenile.",
  "irritation": "A word meaning: The state of being irritated.",
  "astrology": "A word meaning: Divination about human affairs or natural phenomena from the relative positions of celestial bodies.",
  "illegible": "A word meaning: Not clear enough to be read; unreadable; not legible or decipherable.",
  "immeasurable": "A word meaning: Impossible to measure.",
  "irrational": "A word meaning: Not rational; unfounded, nonsensical or wrong-headed.",
  "astronomy": "A word meaning: The study of the physical universe beyond the Earth's atmosphere, including the process of mapping locations and properties of the matter and..."
};
